<?php
/**
 * Created by PhpStorm.
 * Author: 火柴<290559038@qq.com>
 * Date: 2018/1/15
 * Time: 23:04
 */

namespace common\models;


use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class Tweeter extends ActiveRecord
{
    public static function tableName()
    {
        return "{{%tweeter}}"; // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className()
        ];
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }


    public function getId()
    {
        return $this->primaryKey();
    }


}